// <auto-generated />
namespace A_Gde_Si_Ti_Pub.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.5.1")]
    public sealed partial class Proizvod_izmenjen : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(Proizvod_izmenjen));
        
        string IMigrationMetadata.Id
        {
            get { return "202510092104367_Proizvod_izmenjen"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
