// <auto-generated />
namespace A_Gde_Si_Ti_Pub.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.5.1")]
    public sealed partial class korisnik : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(korisnik));
        
        string IMigrationMetadata.Id
        {
            get { return "202510112003484_korisnik"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
